/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Julian Andres Duarte
 */
public class Libros extends javax.swing.JFrame {
static operaciones opera = new operaciones();
    /**
     * Creates new form Libros
     */
    public Libros() {
        initComponents();
    }
    public void limpiar()
    {
        text_id_Libro.setText("");
        text_autor.setText("");
        text_anno_publicacion.setText("");
        text_titulo.setText("");
        text_area_conocimiento.setText("");
        text_edicion.setText("");
        text_editorial.setText("");
    }
    public void habilitar()
    {
        text_anno_publicacion.setEnabled(true);
        text_area_conocimiento.setEnabled(true);
        text_autor.setEnabled(true);
        text_edicion.setEnabled(true);
        text_editorial.setEnabled(true);
        text_titulo.setEnabled(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bottoncrear = new javax.swing.JToggleButton();
        botton_borrar = new javax.swing.JToggleButton();
        text_id_Libro = new javax.swing.JTextField();
        text_area_conocimiento = new javax.swing.JTextField();
        text_editorial = new javax.swing.JTextField();
        text_edicion = new javax.swing.JTextField();
        text_autor = new javax.swing.JTextField();
        text_titulo = new javax.swing.JTextField();
        text_anno_publicacion = new javax.swing.JTextField();
        box_coleccion = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LIBROS");

        jLabel2.setText("ID LIBRO");

        jLabel3.setText("AUTOR");

        jLabel4.setText("AÑO PUBLICACIÓN");

        jLabel5.setText("TITULO");

        jLabel6.setText("EDITORIAL");

        jLabel7.setText("AREA CONOCIMIENTO");

        jLabel8.setText("EDICIÓN");

        jLabel9.setText("COLECCIÓN");

        bottoncrear.setText("CREAR");
        bottoncrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bottoncrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bottoncrear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bottoncrearItemStateChanged(evt);
            }
        });
        bottoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoncrearActionPerformed(evt);
            }
        });

        botton_borrar.setText("BORRAR");
        botton_borrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_borrarActionPerformed(evt);
            }
        });

        text_id_Libro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_id_LibroKeyTyped(evt);
            }
        });

        text_anno_publicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_anno_publicacionKeyTyped(evt);
            }
        });

        box_coleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "general", "reserva" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(bottoncrear)
                        .addGap(71, 71, 71)
                        .addComponent(botton_borrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_autor)
                            .addComponent(text_anno_publicacion)
                            .addComponent(text_id_Libro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_edicion)
                                    .addComponent(text_editorial)
                                    .addComponent(text_area_conocimiento)
                                    .addComponent(text_titulo)
                                    .addComponent(box_coleccion, 0, 163, Short.MAX_VALUE))
                                .addGap(0, 10, Short.MAX_VALUE)))))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_id_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_anno_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(text_area_conocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(text_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(text_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(box_coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottoncrear)
                    .addComponent(botton_borrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_id_LibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_id_LibroKeyTyped
    char c = evt.getKeyChar();
        if (c<'0'||c>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_text_id_LibroKeyTyped

    private void text_anno_publicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_anno_publicacionKeyTyped
     char c = evt.getKeyChar();
        if (c<'0'||c>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_text_anno_publicacionKeyTyped

    private void bottoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoncrearActionPerformed
    habilitar();
    opera.ingreso(String.format("insert into libro values(%d,'%s',%d,'%s')", Integer.parseInt(this.text_id_Libro.getText()),this.text_autor.getText(),Integer.parseInt(this.text_anno_publicacion.getText()),this.text_titulo.getText()));
    opera.ingreso(String.format("insert into topologia values(%d,'%s','%s','%s','%s')", Integer.parseInt(this.text_id_Libro.getText()),this.text_area_conocimiento.getText(),this.text_editorial.getText(),this.text_edicion.getText(),this.box_coleccion.getSelectedItem()));
    limpiar();
    }//GEN-LAST:event_bottoncrearActionPerformed

    private void botton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_borrarActionPerformed
    text_id_Libro.setEditable(true);
    text_anno_publicacion.setEnabled(false);
    text_area_conocimiento.setEnabled(false);
    text_autor.setEnabled(false);
    text_edicion.setEnabled(false);
    text_editorial.setEnabled(false);
    text_titulo.setEnabled(false);
    opera.ingreso(String.format("delete  from topologia where id_libro = %d", Integer.parseInt(this.text_id_Libro.getText())));
    opera.ingreso(String.format("delete  from libro where id_libro = %d", Integer.parseInt(this.text_id_Libro.getText())));
    limpiar();
    }//GEN-LAST:event_botton_borrarActionPerformed

    private void bottoncrearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bottoncrearItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bottoncrearItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botton_borrar;
    private javax.swing.JToggleButton bottoncrear;
    private javax.swing.JComboBox<String> box_coleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_anno_publicacion;
    private javax.swing.JTextField text_area_conocimiento;
    private javax.swing.JTextField text_autor;
    private javax.swing.JTextField text_edicion;
    private javax.swing.JTextField text_editorial;
    private javax.swing.JTextField text_id_Libro;
    private javax.swing.JTextField text_titulo;
    // End of variables declaration//GEN-END:variables
}
